More engines!
AtomLinter/linter-codeclimate pull request #66
Opened 2017-04-19 16:36 UTC by cgalvarez

Adds more engines to JavaScript, PHP, Markdown, Python.

Also adds engines for CSS and shell (which I miss a lot!).

2017-04-19 16:38 UTC, Arcanemagus approved these changes
Syntax looks good to me, I'll leave whether those are valid to @maxjacobson to comment on!

2017-04-19 19:54 UTC, maxjacobson requested changes

2017-04-19 19:54 UTC, maxjacobson commented on lib/index.js
> +      JavaScript: ['checks', 'eslint', 'nodesecurity', 'requiresafe'],
for now, will you remove `checks`? It's not quite ready for public consumption

2017-04-19 19:55 UTC, maxjacobson commented
@Arcanemagus Thanks for the ping. Btw, will you add @ale7714 to the codeclimate-specific team? She can help out with giving CC-specific perspective and review

2017-04-19 20:01 UTC, Arcanemagus commented
Promoted you to team maintainer, does that give you permissions to add people from outside the org, or just ones already in the org?

2017-04-19 20:05 UTC, maxjacobson commented
@Arcanemagus Ah, thanks. nly ones already in the org though

2017-04-19 20:28 UTC, Arcanemagus commented
Ah, dang, I'll add her then 😉.

2017-04-20 09:23 UTC, cgalvarez commented
@maxjacobson `checks` removed :wink:

2017-04-20 15:38 UTC, maxjacobson requested changes

2017-04-20 15:38 UTC, maxjacobson commented on lib/index.js
>        'Ruby on Rails (RJS)': ['rubocop', 'reek'],
will you also please add `flog` to these three ruby-related mappings?

2017-04-20 16:42 UTC, cgalvarez commented on lib/index.js
>        'Ruby on Rails (RJS)': ['rubocop', 'reek'],
Sure. Already sent. There you have'em.

2017-04-20 18:02 UTC, maxjacobson approved these changes

2017-04-20 18:52 UTC, merged